/* Generated By:JavaCC: Do not edit this line. EsiParserConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface EsiParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int LETTER = 5;
  /** RegularExpression Id. */
  int NUMBER = 6;
  /** RegularExpression Id. */
  int SEMICOLON = 7;
  /** RegularExpression Id. */
  int DOUBLEDOT = 8;
  /** RegularExpression Id. */
  int EQUAL = 9;
  /** RegularExpression Id. */
  int NOTEQUAL = 10;
  /** RegularExpression Id. */
  int DOUBLEDOUBLEDOT = 11;
  /** RegularExpression Id. */
  int ASSIGN = 12;
  /** RegularExpression Id. */
  int OPENTAG = 13;
  /** RegularExpression Id. */
  int CLOSETAG = 14;
  /** RegularExpression Id. */
  int OPENPAR = 15;
  /** RegularExpression Id. */
  int CLOSEPAR = 16;
  /** RegularExpression Id. */
  int COMMA = 17;
  /** RegularExpression Id. */
  int IF = 18;
  /** RegularExpression Id. */
  int THEN = 19;
  /** RegularExpression Id. */
  int DEBUT = 20;
  /** RegularExpression Id. */
  int FIN = 21;
  /** RegularExpression Id. */
  int INTERFACE = 22;
  /** RegularExpression Id. */
  int INIT = 23;
  /** RegularExpression Id. */
  int ACT = 24;
  /** RegularExpression Id. */
  int PLUS = 25;
  /** RegularExpression Id. */
  int ACTION = 26;
  /** RegularExpression Id. */
  int NEXTACTION = 27;
  /** RegularExpression Id. */
  int COMP = 28;
  /** RegularExpression Id. */
  int OPERATION = 29;
  /** RegularExpression Id. */
  int EVET = 30;
  /** RegularExpression Id. */
  int PROP = 31;
  /** RegularExpression Id. */
  int COMPONENT = 32;
  /** RegularExpression Id. */
  int ID = 33;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\r\\n\"",
    "<LETTER>",
    "<NUMBER>",
    "\";\"",
    "\":\"",
    "\"=\"",
    "\"<>\"",
    "<DOUBLEDOUBLEDOT>",
    "<ASSIGN>",
    "\"{\"",
    "\"}\"",
    "\"(\"",
    "\")\"",
    "\",\"",
    "\"if\"",
    "\"then\"",
    "\"DEBUT\"",
    "\"FIN\"",
    "\"INTERFACE\"",
    "\"INITIALISATIONS\"",
    "\"ACTIONS\"",
    "\"+\"",
    "<ACTION>",
    "<NEXTACTION>",
    "\"COMP\"",
    "<OPERATION>",
    "<EVET>",
    "\"PROP\"",
    "<COMPONENT>",
    "<ID>",
  };

}
